version: "3.8"

services:
  legal_assistant:
    build:
      context: .
      dockerfile: Dockerfile
    image: legal_assistant
    env_file:
      - .env
    restart: always
    ports:
      - "8003:8003"